### ISSUE TITLE
ENC_XOR ={ 12, 57, 251, 120, 18, 75, 6, 250, 85 }

### ISSUE THREAD

**Issue by MichaelVanHouHei** [carry0987/MegaDownloader#1]
Private Shared ENC_XOR As Byte() = New Byte() {12, 57, 251, 120, 18, 75, 6, 250, 85} ' REMOVED FROM SOURCE CODE, SORRY

**Comment by carry0987** [comment]
> Private Shared ENC_XOR As Byte() = New Byte() {12, 57, 251, 120, 18, 75, 6, 250, 85} ' REMOVED FROM SOURCE CODE, SORRY

Added
